public class MathUtility {
    
    public static Integer addNumbers(Integer a, Integer b) {
        return a + b;
    }

    public static Integer multiplyNumbers(Integer a, Integer b) {
        return a * b;
    }
    
    public static Integer divideNumbers(Integer a, Integer b) {
        return a / b;
    }
   public static Integer substractNumbers(Integer a, Integer b) {
        return a - b;
    }
  
     
    public static Integer divideNumbers1(Integer a, Integer b) {
        return a / b;
    }
}